# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EstadosPedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Estados')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pedido', models.CharField(max_length=250)),
                ('num_pedido', models.CharField(default=b'1', max_length=15)),
                ('concepto', models.CharField(blank=True, max_length=200)),
                ('telefono_ubicacion', models.CharField(blank=True, max_length=12)),
                ('forma_de_recepcion', models.CharField(blank=True, max_length=30)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Estados')),
                ('producto', models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='productos.Producto')),
                ('usuario', models.ForeignKey(default=b'1', on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuarios')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.AddField(
            model_name='estadospedidos',
            name='num_pedido',
            field=models.ForeignKey(default=b'1', on_delete=django.db.models.deletion.CASCADE, to='pedidos.Pedido'),
        ),
    ]
