# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(default=b'', max_length=250)),
                ('correo_electronico', models.CharField(default=b'', max_length=300)),
                ('password', models.CharField(default=b'12345', max_length=30)),
                ('rol', models.CharField(default=b'', max_length=30)),
            ],
        ),
    ]
