# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=250)),
                ('categoria', models.CharField(max_length=250)),
                ('producto_foto', models.CharField(max_length=1000)),
            ],
        ),
    ]
